"""First-run auto-provisioning for Bitmod.

Detects fresh installs and automatically sets up everything a user needs:
database, configuration, API key, and optional dependencies.

Usage (programmatic):
    from bitmod.setup import run_first_time_setup, is_fresh_install

    if is_fresh_install():
        result = run_first_time_setup()
        print(f"API key: {result['api_key']}")

Usage (CLI):
    bitmod init      # Interactive first-time setup
    bitmod doctor    # Health check
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

DEFAULT_DATA_DIR = os.path.expanduser("~/.bitmod")
DEFAULT_DB_PATH = os.path.join(DEFAULT_DATA_DIR, "bitmod.db")
DEFAULT_CONFIG_PATH = os.path.join(DEFAULT_DATA_DIR, "bitmod.yaml")


# ---------------------------------------------------------------------------
# Data directory
# ---------------------------------------------------------------------------


def ensure_data_directory(data_dir: str = DEFAULT_DATA_DIR) -> str:
    """Create the BitMod data directory if it doesn't exist."""
    os.makedirs(data_dir, exist_ok=True)
    # Create subdirectories for backups, logs, models
    for subdir in ("backups", "logs", "models"):
        os.makedirs(os.path.join(data_dir, subdir), exist_ok=True)
    return data_dir


def is_fresh_install(data_dir: str = DEFAULT_DATA_DIR) -> bool:
    """Check if this is a first-time setup."""
    return not os.path.exists(os.path.join(data_dir, "bitmod.db"))


# ---------------------------------------------------------------------------
# Database initialization
# ---------------------------------------------------------------------------


def initialize_database(db_path: str = DEFAULT_DB_PATH) -> None:
    """Initialize the SQLite database with all required tables.

    Also runs any pending migrations from db/migrations/.
    """
    from bitmod.adapters.db_sqlite import SQLiteBackend

    backend = SQLiteBackend(db_path)
    backend.initialize()

    # Run pending migrations
    try:
        from bitmod.migrations import MigrationRunner

        runner = MigrationRunner(backend)
        with backend.session() as session:
            applied = runner.migrate(session)
            if applied:
                logger.info("Applied %d migration(s) during setup", len(applied))
    except Exception as exc:
        logger.warning("Migration runner skipped: %s", exc)

    logger.info("Database initialized at %s", db_path)


# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------


def generate_default_config(
    config_path: str = DEFAULT_CONFIG_PATH,
    data_dir: str = DEFAULT_DATA_DIR,
    overrides: dict[str, Any] | None = None,
) -> dict:
    """Generate a default bitmod.yaml with sensible defaults.

    Returns the config dict that was written.
    """
    db_path = os.path.join(data_dir, "bitmod.db")

    config = {
        "# Bitmod Configuration": None,
        "# Generated by: bitmod init": None,
        "# Docs: https://github.com/DeepanjayNandal/bitmod": None,
        "db_backend": "sqlite",
        "db_sqlite_path": db_path,
        "llm_primary": "ollama",
        "llm_primary_model": "llama3.2",
        "llm_fallback": "ollama",
        "llm_fallback_model": "llama3.2",
        "embedding_provider": "ollama",
        "embedding_model": "nomic-embed-text",
        "embedding_dimensions": "768",
        "gateway_port": 8000,
    }

    if overrides:
        config.update(overrides)

    # Write as YAML — use a simple manual approach to preserve comments
    lines = [
        "# Bitmod Configuration",
        "# Generated by: bitmod init",
        "# Docs: https://github.com/DeepanjayNandal/bitmod",
        "",
        "# Database",
        "db_backend: sqlite",
        f"db_sqlite_path: {db_path}",
        "",
        "# LLM Provider",
        f"llm_primary: {config.get('llm_primary', 'ollama')}",
        f"llm_primary_model: {config.get('llm_primary_model', 'llama3.2')}",
        f"llm_fallback: {config.get('llm_fallback', 'ollama')}",
        f"llm_fallback_model: {config.get('llm_fallback_model', 'llama3.2')}",
        "",
        "# Embedding Provider",
        f"embedding_provider: {config.get('embedding_provider', 'ollama')}",
        f"embedding_model: {config.get('embedding_model', 'nomic-embed-text')}",
        f"embedding_dimensions: {config.get('embedding_dimensions', '768')}",
        "",
        "# API Server",
        f"gateway_port: {config.get('gateway_port', 8000)}",
    ]

    os.makedirs(os.path.dirname(config_path), exist_ok=True)
    Path(config_path).write_text("\n".join(lines) + "\n")

    logger.info("Config written to %s", config_path)
    return config


# ---------------------------------------------------------------------------
# API key generation
# ---------------------------------------------------------------------------


def generate_api_key(db_path: str = DEFAULT_DB_PATH) -> str:
    """Generate a default admin API key and store it in the database.

    Returns the plaintext API key (only shown once).
    """
    from bitmod.adapters.db_sqlite import SQLiteBackend
    from bitmod.auth import APIKeyManager

    backend = SQLiteBackend(db_path)
    backend.initialize()
    manager = APIKeyManager(backend)
    key, _record = manager.create_key(
        name="default-admin",
        owner="system",
        scopes=["read", "write", "admin"],
    )
    return key


# ---------------------------------------------------------------------------
# Dependency checking
# ---------------------------------------------------------------------------

_OPTIONAL_DEPS = [
    ("anthropic", "anthropic", "Anthropic Claude LLM"),
    ("openai", "openai", "OpenAI GPT LLM"),
    ("gemini", "google.generativeai", "Google Gemini LLM"),
    ("ollama", "ollama", "Ollama local LLM"),
    ("embeddings", "sentence_transformers", "Local embedding models"),
    ("postgresql", "asyncpg", "PostgreSQL database"),
    ("mysql", "pymysql", "MySQL database"),
    ("mongodb", "pymongo", "MongoDB database"),
    ("redis", "redis", "Redis cache"),
    ("chroma", "chromadb", "ChromaDB vector store"),
    ("qdrant", "qdrant_client", "Qdrant vector store"),
    ("pinecone", "pinecone", "Pinecone vector store"),
    ("pdf", "fitz", "PDF ingestion (PyMuPDF)"),
    ("docx", "docx", "DOCX ingestion"),
    ("html", "bs4", "HTML ingestion (BeautifulSoup)"),
    ("metrics", "prometheus_client", "Prometheus metrics"),
    ("server", "fastapi", "FastAPI server"),
    ("jwt", "jwt", "JWT authentication (PyJWT)"),
]


def check_dependencies() -> dict[str, dict[str, Any]]:
    """Check which optional dependencies are available.

    Returns dict of {name: {"available": bool, "description": str}}.
    """
    deps: dict[str, dict[str, Any]] = {}
    for name, package, description in _OPTIONAL_DEPS:
        available = False
        try:
            __import__(package)
            available = True
        except ImportError:
            pass
        deps[name] = {"available": available, "description": description}
    return deps


# ---------------------------------------------------------------------------
# Embedding model download
# ---------------------------------------------------------------------------


def download_embedding_model(
    model_name: str = "sentence-transformers/all-MiniLM-L6-v2",
) -> bool:
    """Pre-download the embedding model for offline use."""
    try:
        from sentence_transformers import SentenceTransformer

        logger.info("Downloading embedding model: %s", model_name)
        SentenceTransformer(model_name)
        logger.info("Embedding model downloaded successfully")
        return True
    except ImportError:
        logger.info("sentence-transformers not installed, skipping model download")
        return False
    except Exception as e:
        logger.warning("Failed to download embedding model: %s", e)
        return False


# ---------------------------------------------------------------------------
# LLM provider connectivity check
# ---------------------------------------------------------------------------


def check_llm_provider(provider: str, model: str = "") -> dict[str, Any]:
    """Check if an LLM provider is reachable.

    Returns {"reachable": bool, "error": str | None}.
    """
    result: dict[str, Any] = {"reachable": False, "error": None}

    if provider == "ollama":
        try:
            import httpx

            url = os.getenv("OLLAMA_URL", "http://localhost:11434")
            resp = httpx.get(f"{url}/api/tags", timeout=5.0)
            result["reachable"] = resp.status_code == 200
            if result["reachable"]:
                data = resp.json()
                models = [m.get("name", "") for m in data.get("models", [])]
                result["models"] = models
                if model and not any(model in m for m in models):
                    result["error"] = f"Model '{model}' not found. Available: {', '.join(models[:5])}"
        except Exception as e:
            result["error"] = f"Cannot reach Ollama: {e}"
    elif provider == "anthropic":
        key = os.getenv("ANTHROPIC_API_KEY", "")
        if not key:
            result["error"] = "ANTHROPIC_API_KEY not set"
        else:
            result["reachable"] = True  # Key exists, assume reachable
    elif provider == "openai":
        key = os.getenv("OPENAI_API_KEY", "")
        if not key:
            result["error"] = "OPENAI_API_KEY not set"
        else:
            result["reachable"] = True
    else:
        # For other providers, just check if the relevant env var is set
        from bitmod.cli import _API_KEY_MAP

        if provider in _API_KEY_MAP:
            env_var, _label = _API_KEY_MAP[provider]
            key = os.getenv(env_var, "")
            if not key:
                result["error"] = f"{env_var} not set"
            else:
                result["reachable"] = True
        else:
            result["reachable"] = True  # Unknown provider, assume OK

    return result


# ---------------------------------------------------------------------------
# Full first-time setup
# ---------------------------------------------------------------------------


def run_first_time_setup(
    data_dir: str = DEFAULT_DATA_DIR,
    interactive: bool = True,
) -> dict[str, Any]:
    """Run the complete first-time setup.

    Steps:
        1. Create data directory (~/.bitmod/)
        2. Initialize SQLite database with all tables
        3. Run pending migrations
        4. Generate default bitmod.yaml config
        5. Generate a default admin API key
        6. Check optional dependencies
        7. Optionally download embedding model

    Returns dict with setup results:
        data_dir, db_path, config_path, api_key, deps, embedding_downloaded.
    """
    result: dict[str, Any] = {
        "data_dir": data_dir,
        "db_path": os.path.join(data_dir, "bitmod.db"),
        "config_path": os.path.join(data_dir, "bitmod.yaml"),
        "api_key": None,
        "deps": {},
        "embedding_downloaded": False,
    }

    # 1. Create data directory
    ensure_data_directory(data_dir)

    # 2. Initialize database
    db_path = result["db_path"]
    initialize_database(db_path)

    # 3. Generate config (skip if already exists)
    config_path = result["config_path"]
    if not os.path.exists(config_path):
        generate_default_config(config_path, data_dir)

    # 4. Generate API key
    try:
        api_key = generate_api_key(db_path)
        result["api_key"] = api_key
    except Exception as exc:
        logger.warning("Failed to generate API key: %s", exc)  # nosemgrep: python-logger-credential-disclosure

    # 5. Check dependencies
    deps = check_dependencies()
    result["deps"] = deps

    # 6. Download embedding model if sentence-transformers is available
    if deps.get("embeddings", {}).get("available", False):
        if interactive:
            # In interactive mode, the CLI will prompt the user
            result["embedding_available"] = True
        else:
            result["embedding_downloaded"] = download_embedding_model()

    return result


# ---------------------------------------------------------------------------
# Auto-setup (called silently by Bitmod() or `bitmod serve`)
# ---------------------------------------------------------------------------


def auto_setup_if_needed(data_dir: str = DEFAULT_DATA_DIR) -> bool:
    """Silently run first-time setup if this is a fresh install.

    Called automatically by Bitmod() constructor and `bitmod serve`.
    Returns True if setup was performed, False if already set up.
    """
    if not is_fresh_install(data_dir):
        return False

    try:
        run_first_time_setup(data_dir=data_dir, interactive=False)
        return True
    except Exception as exc:
        logger.warning("Auto-setup failed: %s", exc)
        return False
